[package]
name = "search_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
search_base = { path = "../search_base" }
tantivy = "0.16"
serde_json = "1.0"