name: Frontend-CI

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm ci --silent
          npm install react-scripts -g --silent
        working-directory: ${{ env.working-directory }}      
      - name: Build
        run: npm run build
        working-directory: ${{ env.working-directory }}    
